# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish 🚀

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: current-time-service
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.x.x
        
    - name: Restore
      run: dotnet restore /USSEnterpriseApplication/USSEnterprise.Presentation/.sln
      
    - name: Build
      run: dotnet build /USSEnterpriseApplication/USSEnterprise.Presentation.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test /USSEnterpriseApplication/USSEnterprise.Presentation.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish /USSEnterpriseApplication/USSEnterprise.Presentation.sln --configuration Release --no-build
