name: Publish 🚀

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: current-time-service
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner for .NET Framework
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.8'  # Use the correct .NET Framework version
        
    - name: Restore
      run: nuget restore USSEnterpriseApplication/USSEnterprise.Presentation.sln
      
    - name: Build
      run: msbuild USSEnterpriseApplication/USSEnterprise.Presentation.sln /p:Configuration=Release
      
    - name: Test
      run: echo "No tests for .NET Framework"
      
    - name: Publish
      run: msbuild USSEnterpriseApplication/USSEnterprise.Presentation.sln /p:Configuration=Release /t:Publish
